const uniquePizzaFacts = [
  "Pizza originated in Naples, Italy, in the 18th century.",
  "The Margherita pizza was named after Queen Margherita of Italy.",
  "The first pizzeria in the United States, Lombardi's, opened in 1905 in New York City.",
  "Americans consume approximately 3 billion pizzas each year.",
  "October is National Pizza Month in the United States.",
  "The world's largest pizza was made in South Africa in 1990, measuring 122 feet and 8 inches in diameter.",
  "The Hawaiian pizza, topped with ham and pineapple, was invented in Canada, not Hawaii.",
  "The most popular pizza topping in the United States is pepperoni.",
  "The record for the longest pizza delivery is 6,131 miles, from London to Melbourne.",
  "The first frozen pizza was introduced in 1957 by Celentano Brothers.",
  "The word 'pizza' dates back over a thousand years and was first documented in A.D. 997 in Gaeta, Italy.",
  "The world's most expensive pizza costs over $12,000 and includes caviar, lobster, and 24-karat gold flakes.",
  "The largest collection of pizza boxes is held by Scott Wiener, who has over 1,000 unique boxes.",
  "Pizza accounts for more than 10% of all food service sales in the United States.",
  "The first online pizza order was placed in 1974 at Pizza Hut.",
  "The famous Chicago deep-dish pizza has a crust that can be over 3 inches tall.",
  "In Japan, mayonnaise and corn are popular pizza toppings.",
  "The world record for the fastest time to eat a 12-inch pizza is 23.62 seconds.",
  "Domino's Pizza was originally named DomiNick's but changed its name in 1965.",
  "The Italian Association of Pizza Makers established the rules for making 'true Neapolitan pizza.'",
  "The world record for the largest pizza ever made weighed over 26,000 pounds and was created in Fiera Roma, Italy.",
  "In Sweden, banana curry pizza is a popular choice, featuring bananas, curry powder, and sometimes peanuts.",
  "The first documented pizzeria in the world is Port'Alba in Naples, which opened in 1830.",
  "The average American consumes about 23 pounds of pizza per year.",
  "The town of Naples has its own organization, the Associazione Verace Pizza Napoletana, dedicated to preserving the authenticity of Neapolitan pizza.",
  "Pizza Hut delivered a pizza to the International Space Station in 2001, making it the first pizza delivery to space.",
  "The world's fastest pizza maker can make 14 pizzas in one minute and 26 seconds.",
  "In 2017, a study found that pizza is the most addictive food, even surpassing chocolate.",
  "Chicago-style pizza is known for its deep-dish crust, but there's also a thin-crust variety known as 'tavern-style' pizza in the Windy City.",
  "The largest pizza chain in the world, in terms of locations, is Domino's Pizza.",
  "In 2013, a pizza delivery driver saved a kidnapped woman after she mouthed 'help me' to him.",
  "The concept of putting pineapple on pizza is divisive, with strong opinions on both sides of the debate.",
  "A study found that the smell of pizza can induce feelings of happiness.",
  "The most expensive pizza ever sold commercially was priced at $2,700 and featured lobster, caviar, and gold leaf.",
  "Pizza is a $45 billion per year industry in the United States.",
  "The first pizza ordered through a computer was done using a touch-tone phone and a computer program called 'Domino's Pizza.'",
  "There's a pizza museum in Philadelphia, called 'Pizza Brain,' featuring pizza memorabilia and artifacts.",
  "The world's largest pizza party took place in Norwood, South Africa, in 1990, with 6,000 participants.",
  "The world's largest pizza box measured 54 square feet and was created in Ontario, Canada.",
  "Pizza was not widely consumed in the United States until after World War II when American soldiers returning from Italy brought a taste for pizza with them.",
  "The first recorded pizzeria in the United States was G. (for Gennaro) Lombardi's Pizzeria, which opened in New York City in 1905.",
  "The 'Meat Lover's' pizza is a popular choice, typically featuring pepperoni, sausage, bacon, and ham.",
  "Pizza delivery drivers have a higher risk of being in a car accident than other drivers due to the time pressure of deliveries.",
  "The world's largest pizza festival is held annually in Naples, attracting thousands of pizza enthusiasts.",
  "A study found that pizza consumption is linked to a lower risk of certain cancers.",
  "The first known pizza cookbook, 'Il Cuoco Galante,' was published in Naples in 1773.",
  "The world record for the most people tossing pizza dough simultaneously is over 2,000 participants.",
  "Pizza was not considered a mainstream food in the United States until the 1950s.",
  "In Australia, kangaroo and emu are used as pizza toppings in some restaurants.",
  "In Italy, there's a law that regulates the ingredients and methods for making authentic Neapolitan pizza.",
  "In 2019, a pizza delivery driver in Wisconsin saved a kidnapped woman after noticing a distraught child in the background of the delivery.",
  "The world's largest pizza box manufacturer is in the United States, producing millions of boxes annually.",
  "In 2008, the town of Naples tried to trademark the Margherita pizza to protect its cultural heritage.",
  "The world's largest pizza delivery chain, Domino's, operates in over 90 countries.",
  "The term 'pizza' is believed to have come from the Latin word 'picea,' meaning the blackening of crust by fire.",
  "In 2013, a pizza delivery driver received a $1,268 tip after delivering pizza to a college dorm.",
  "The world record for the most pizzas made in one hour by a team of two is 565 pizzas.",
  "Some pizzerias offer dessert pizzas with sweet toppings like chocolate, fruit, and marshmallows.",
  "In 2001, Pizza became the most popular takeout food in the United States, surpassing hamburgers.",
  "Pizza has inspired various forms of art, including the famous painting 'The Pizza Eaters' by Salvador Dali.",
  "The town of Sault Ste. Marie in Canada holds an annual 'Polar Bear Swim and Pizza Party' on New Year's Day.",
  "The first online pizza order was a large pepperoni and mushroom pizza from Pizza Hut in 1994.",
  "The world record for the longest pizza delivery route is over 15,000 miles, from Melbourne, Australia, to Rome, Italy.",
  "The idea of putting pineapple on pizza is credited to Canadian chef Sam Panopoulos in the 1960s.",
  "A study found that the smell of pizza could increase men's arousal by 5%.",
  "In Japan, mayonnaise and corn are popular pizza toppings.",
  "Pizza delivery bags are designed to keep pizzas hot and fresh during transportation.",
  "The world record for the largest circular pizza spun in 30 seconds is 3.88 meters in diameter.",
  "The city of Chicago celebrates 'National Deep Dish Pizza Day' every April 5th.",
  "In 2018, a delivery driver in Oregon helped rescue two girls from a potential kidnapping while on the job.",
  "The world record for the most people making pizzas simultaneously is over 2,000 participants.",
  "In 2010, a pizza delivery driver in England was awarded a medal for saving a choking customer while on a delivery.",
  "A study found that people who eat pizza regularly have a higher intake of key nutrients, including calcium and potassium.",
  "In Russia, it's common to find pizzas topped with ingredients like red herring and sardines.",
  "The world record for the largest collection of pizza-related items is held by Scott Wiener, who has over 1,500 unique pieces.",
  "Pizza Hut introduced the first online pizza ordering system in 1994.",
  "The town of Naples has strict rules for what constitutes a traditional Neapolitan pizza, including specific ingredients and preparation methods.",
  "The world record for the largest number of people tossing pizza dough simultaneously is over 3,000 participants.",
  "The city of New York has its own unique style of pizza, characterized by thin, foldable slices.",
  "The concept of a dessert pizza originated in Italy, featuring sweet toppings like Nutella, fruits, or chocolate.",
  "In 2016, a pizzeria in California created a record-breaking pizza topped with over 100 varieties of cheese.",
  "The town of Naples hosts an annual pizza festival called 'Pizza Village,' celebrating the diversity of pizza styles.",
  "Some pizza enthusiasts celebrate 'National Cheese Pizza Day' on September 5th each year.",
  "Pizza tossing, also known as acrobatics, is a skillful technique where pizza dough is spun and tossed in the air.",
  "Pizza has inspired various music genres, and there are songs dedicated to the love of pizza.",
  "A pizzeria in Alaska holds the record for being the northernmost pizzeria in the world.",
  "Pizza has been delivered to the top of Mount Everest, making it the highest pizza delivery on record.",
  "There's a trend called 'pizza farms,' where farms host pizza nights using fresh, locally-sourced ingredients.",
  "A pizzeria in Japan created a pizza with a crust made entirely of sushi rice and topped with sashimi.",
  "The town of Naples is so passionate about pizza that they have a patron saint of pizza makers, Saint Anthony Abate.",
  "There's a competitive event called the 'World Pizza Games,' where pizza chefs showcase their skills in various pizza-related challenges.",
  "In 2015, a pizza delivery driver in the UK was caught attempting to deliver pizza while riding a hoverboard.",
  "Some pizzerias offer unique pizza crust alternatives, such as cauliflower crust or gluten-free crust.",
  "Pizza box technology has evolved, with innovations like perforated boxes that can be transformed into plates.",
  "Pizza has made appearances in numerous movies and TV shows, becoming a cultural icon in popular media.",
  "A pizzeria in Iowa holds the record for the longest pizza delivery, covering a distance of over 1,000 miles.",
  "Pizza tossing has been recognized as a sport, and there are competitions where participants showcase their dough-spinning skills.",
  "A pizzeria in New Zealand created a Guinness World Record by cooking 338 different types of pizzas in one hour.",
  "In 2014, the town of Naples attempted to break the record for the longest pizza, reaching over 1.8 kilometers.",
  "Pizza has inspired the creation of pizza-flavored snacks, including potato chips, pretzels, and even ice cream.",
  "A pizzeria in Scotland offers a 'Monster Pizza' challenge, where participants have to finish a giant pizza within a set time to win a prize.",
  "There's a trend of 'pizza cones,' where pizza ingredients are served in a cone-shaped crust for a portable pizza experience.",
  "Some pizza delivery vehicles are equipped with special ovens to ensure pizzas stay hot during transit.",
  "A pizzeria in Australia holds the record for the largest variety of pizzas on its menu, offering over 150 different options.",
  "Pizza has become a popular wedding dish, with some couples opting for pizza buffets at their receptions.",
  "A pizzeria in London offers a 'bottomless' pizza brunch, allowing customers to enjoy unlimited pizza slices during a specific time.",
  "There's a pizzeria in Florida that delivers pizzas by boat to customers living on remote islands.",
  "A pizzeria in Sweden created a pizza with a crust made from insects, promoting sustainability and protein-rich diets.",
  "A pizza festival in Naples once featured a pizza that measured over 2 kilometers in length.",
  "Some pizzerias offer pizza-making classes, allowing customers to learn the art of pizza crafting.",
  "A pizzeria in Japan offers a 'fortune-telling pizza,' where the toppings are selected based on your astrological sign.",
  "A pizza place in California introduced a pizza topped with 24-karat gold flakes, creating a luxurious culinary experience.",
  "Pizza Hut holds the record for the world's largest delivery fleet, with thousands of delivery drivers worldwide.",
  "The town of Naples hosts an annual 'Pizza Day' where pizzerias offer discounts and promotions to celebrate the beloved dish.",
  "There's a pizzeria in Sweden that specializes in 'surströmming pizza,' featuring the infamous Swedish fermented herring as a topping.",
  "Pizza consumption tends to increase during major sporting events, making it a popular choice for game nights.",
  "A pizzeria in Japan offers a unique 'ramen pizza,' combining the flavors of traditional Japanese ramen with pizza ingredients.",
  "The town of Naples declared pizza-making a UNESCO intangible cultural heritage in 2017, recognizing its cultural significance.",
  "Some pizzerias use wood-fired ovens, which can reach temperatures of up to 800 degrees Fahrenheit for a quick and crispy bake.",
  "In 2019, a pizzeria in Rome created a pizza with a Guinness World Record-breaking 100 types of cheese.",
  "Pizza has inspired the creation of pizza-flavored beverages, including pizza-flavored soda and beer.",
  "There's a pizzeria in Scotland that offers a 'haggis pizza,' featuring the traditional Scottish dish made from sheep's organs.",
  "A pizzeria in Brazil created a pizza with a vibrant rainbow-colored crust, using natural fruit extracts for coloring.",
  "Pizza boxes are often designed with ventilation holes to prevent the crust from becoming soggy during delivery.",
  "The world's largest pizza expo, 'International Pizza Expo,' takes place annually in Las Vegas, attracting pizza enthusiasts and industry professionals.",
  "A pizzeria in Chicago offers a 'Gold Coast' pizza, featuring luxurious toppings like truffles, caviar, and gold leaf.",
  "There's a pizzeria in California that offers a 'Cheetos pizza,' incorporating the popular snack as a topping.",
  "In 2018, a pizzeria in Italy attempted to break the record for the most pizzas made in one hour, achieving a total of 509 pizzas.",
  "Some pizzerias offer 'breakfast pizzas' with morning-friendly toppings like eggs, bacon, and sausage.",
  "A pizzeria in South Korea created a 'goguma pizza,' featuring sweet potato crust and unique Korean toppings.",
  "Pizza tossing competitions often include categories such as freestyle tossing, fastest toss, and most creative routine.",
  "A pizzeria in New York offers a 'spaghetti and meatball pizza,' combining the classic Italian-American flavors into a pizza format.",
  "There's a pizzeria in Australia that offers a 'Kangaroo Supreme' pizza, featuring kangaroo meat as a topping.",
  "A pizzeria in India created a 'butter chicken pizza,' combining the flavors of the popular Indian dish with pizza.",
  "Some pizzerias offer seasonal pizzas, featuring ingredients that are in season at a particular time of the year.",
  "A pizzeria in London created a pizza with a crust made from charcoal-infused dough, giving it a unique black color.",
  "Pizza tossing has been featured in world records, with the longest continuous pizza toss lasting over 16 hours.",
  "There's a pizzeria in Canada that offers a 'poutine pizza,' combining the flavors of the iconic Canadian dish with pizza toppings.",
  "Pizza has become a popular choice for wedding proposals, with some individuals hiding engagement rings in pizza boxes.",
  "A pizzeria in Texas offers a 'brisket pizza,' featuring the regional specialty of slow-cooked brisket as a topping.",
  "Some pizzerias offer 'dessert pizzas' with sweet toppings like chocolate, marshmallows, and fruit.",
  "A pizzeria in Louisiana created a 'Crawfish Étouffée Pizza,' combining the flavors of the local Cajun dish with pizza.",
];
export default uniquePizzaFacts;
