export const pizzaMakingTips = [
  "Use high-quality and fresh ingredients for the best flavor.",
  "Allow the pizza dough to rise properly for a light and airy crust.",
  "Preheat your oven and pizza stone or baking sheet to ensure a crispy crust.",
  "Stretch the pizza dough evenly to achieve a uniform thickness.",
  "Use a combination of tomato sauce and fresh mozzarella for authentic taste.",
  "Experiment with different cheeses to add variety and richness to your pizza.",
  "Don't overload your pizza with toppings to prevent a soggy crust.",
  "Consider adding fresh herbs like basil or oregano for added freshness.",
  "Brush the crust with olive oil before baking for a golden and flavorful finish.",
  "Try different sauces, such as pesto or garlic butter, for unique flavor profiles.",
  "Invest in a pizza peel for easy transfer of the pizza to and from the oven.",
  "Rotate the pizza halfway through baking for even cooking.",
  "Let the pizza rest for a few minutes before slicing to allow the cheese to set.",
  "Experiment with different crust types, such as thin crust, deep-dish, or stuffed crust.",
  "Use a pizza stone or steel for a crispier crust, especially if baking in a home oven.",
  "Consider grilling your pizza for a smoky flavor and a charred crust.",
  "Try making your own pizza sauce with fresh tomatoes and herbs.",
  "Precook certain toppings like sausage or mushrooms to ensure they are fully cooked on the pizza.",
  "If using a wood-fired oven, manage the fire and temperature carefully for the perfect pizza.",
  "Get creative with toppings – think outside the traditional pizza toppings for unique combinations.",
  "Experiment with different flours for the pizza dough, such as whole wheat or gluten-free options.",
  "If making a thin-crust pizza, roll the dough out as thin as possible for a crispier result.",
  "Use a pizza cutter or sharp knife for clean and easy slicing.",
  "Consider pre-baking the crust for a few minutes before adding toppings for extra crispiness.",
  "Let the dough come to room temperature before stretching to make it more pliable.",
  "Clean and maintain your pizza stone or baking sheet regularly for consistent results.",
  "Allow the pizza to cool slightly before slicing to avoid burning your mouth.",
  "Share the joy of making and enjoying pizza with friends and family!",
];
